/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Victor
 */
public class VistaPrincipalAdmin extends javax.swing.JFrame {
    
    /**
     * Creates new form VistaPrincipal
     */
    int xMouse, yMouse;
    
    
    public VistaPrincipalAdmin() {
        initComponents();
        iniciarlizarContenido();
        
    }
    
    public void hoverButtonsEntered(JButton boton){
        //boton.setBackground(new Color(156, 221, 240));
    }
    
    public void hoverButtonExited(JButton boton){
       // boton.setBackground(new Color(158, 255, 255));
    }
    
    // Cambio entre paneles (Implementacion temporal)
    private void iniciarlizarContenido(){
        agregarJPanel(new VistaInicioAdmin(), "INICIO");
    }
    
    // metodo para resumir el mostrar paneles
    private void agregarJPanel(JPanel p, String titulo){
        p.setSize(968, 617);
        p.setLocation(0,0);
        
        pnContenido.removeAll();
        pnContenido.add(p, BorderLayout.CENTER);
        pnContenido.revalidate();
        pnContenido.repaint();
        
        //Cambio el titulo
        lbTitulo.setText(titulo);
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBg = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        lbMenuTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnRegistroEntregas = new javax.swing.JButton();
        btnEncargos = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnPrendas = new javax.swing.JButton();
        btnUniformes = new javax.swing.JButton();
        btnColegios = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnRegistroUsers = new javax.swing.JButton();
        btnMateriales = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnRegistroMateriales = new javax.swing.JButton();
        pnTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbBienvenida = new javax.swing.JLabel();
        pnHeader = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        lbExit = new javax.swing.JLabel();
        pnContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnBg.setBackground(new java.awt.Color(255, 255, 255));

        pnMenu.setBackground(new java.awt.Color(201, 239, 228));
        pnMenu.setPreferredSize(new java.awt.Dimension(300, 740));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMenuTitle.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        lbMenuTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuTitle.setText("Administración Prendas");
        lbMenuTitle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenuTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuTitleMouseClicked(evt);
            }
        });
        pnMenu.add(lbMenuTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 288, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        pnMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 288, 10));

        btnRegistroEntregas.setBackground(new java.awt.Color(212, 255, 242));
        btnRegistroEntregas.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistroEntregas.setText("Registro de Encargos/Pedidos");
        btnRegistroEntregas.setBorder(null);
        btnRegistroEntregas.setBorderPainted(false);
        btnRegistroEntregas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroEntregasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroEntregasMouseExited(evt);
            }
        });
        btnRegistroEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroEntregasActionPerformed(evt);
            }
        });
        pnMenu.add(btnRegistroEntregas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 300, 44));

        btnEncargos.setBackground(new java.awt.Color(212, 255, 242));
        btnEncargos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEncargos.setText("Lista de Encargos/Pedidos");
        btnEncargos.setBorder(null);
        btnEncargos.setBorderPainted(false);
        btnEncargos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEncargos.setMaximumSize(new java.awt.Dimension(58, 17));
        btnEncargos.setMinimumSize(new java.awt.Dimension(58, 17));
        btnEncargos.setPreferredSize(new java.awt.Dimension(58, 17));
        btnEncargos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEncargosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEncargosMouseExited(evt);
            }
        });
        btnEncargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncargosActionPerformed(evt);
            }
        });
        pnMenu.add(btnEncargos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, 44));

        btnClientes.setBackground(new java.awt.Color(212, 255, 242));
        btnClientes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.setBorder(null);
        btnClientes.setBorderPainted(false);
        btnClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientes.setMaximumSize(new java.awt.Dimension(58, 17));
        btnClientes.setMinimumSize(new java.awt.Dimension(58, 17));
        btnClientes.setPreferredSize(new java.awt.Dimension(58, 17));
        btnClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientesMouseExited(evt);
            }
        });
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        pnMenu.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 300, 44));

        btnPrendas.setBackground(new java.awt.Color(212, 255, 242));
        btnPrendas.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnPrendas.setText("Prendas");
        btnPrendas.setBorder(null);
        btnPrendas.setBorderPainted(false);
        btnPrendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrendas.setMaximumSize(new java.awt.Dimension(58, 17));
        btnPrendas.setMinimumSize(new java.awt.Dimension(58, 17));
        btnPrendas.setPreferredSize(new java.awt.Dimension(58, 17));
        btnPrendas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrendasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrendasMouseExited(evt);
            }
        });
        btnPrendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrendasActionPerformed(evt);
            }
        });
        pnMenu.add(btnPrendas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 300, 44));

        btnUniformes.setBackground(new java.awt.Color(212, 255, 242));
        btnUniformes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnUniformes.setText("Uniformes");
        btnUniformes.setBorder(null);
        btnUniformes.setBorderPainted(false);
        btnUniformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUniformes.setMaximumSize(new java.awt.Dimension(58, 17));
        btnUniformes.setMinimumSize(new java.awt.Dimension(58, 17));
        btnUniformes.setPreferredSize(new java.awt.Dimension(58, 17));
        btnUniformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUniformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUniformesMouseExited(evt);
            }
        });
        btnUniformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniformesActionPerformed(evt);
            }
        });
        pnMenu.add(btnUniformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 300, 44));

        btnColegios.setBackground(new java.awt.Color(212, 255, 242));
        btnColegios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnColegios.setText("Colegios");
        btnColegios.setBorder(null);
        btnColegios.setBorderPainted(false);
        btnColegios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColegios.setMaximumSize(new java.awt.Dimension(58, 17));
        btnColegios.setMinimumSize(new java.awt.Dimension(58, 17));
        btnColegios.setPreferredSize(new java.awt.Dimension(58, 17));
        btnColegios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnColegiosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnColegiosMouseExited(evt);
            }
        });
        btnColegios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColegiosActionPerformed(evt);
            }
        });
        pnMenu.add(btnColegios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 300, 44));

        btnProveedores.setBackground(new java.awt.Color(212, 255, 242));
        btnProveedores.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.setBorder(null);
        btnProveedores.setBorderPainted(false);
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProveedores.setMaximumSize(new java.awt.Dimension(58, 17));
        btnProveedores.setMinimumSize(new java.awt.Dimension(58, 17));
        btnProveedores.setPreferredSize(new java.awt.Dimension(58, 17));
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseExited(evt);
            }
        });
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        pnMenu.add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 300, 44));

        btnRegistroUsers.setBackground(new java.awt.Color(212, 255, 242));
        btnRegistroUsers.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistroUsers.setText("Registro de usuarios");
        btnRegistroUsers.setBorder(null);
        btnRegistroUsers.setBorderPainted(false);
        btnRegistroUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroUsers.setMaximumSize(new java.awt.Dimension(58, 17));
        btnRegistroUsers.setMinimumSize(new java.awt.Dimension(58, 17));
        btnRegistroUsers.setPreferredSize(new java.awt.Dimension(58, 17));
        btnRegistroUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroUsersMouseExited(evt);
            }
        });
        btnRegistroUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroUsersActionPerformed(evt);
            }
        });
        pnMenu.add(btnRegistroUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 300, 44));

        btnMateriales.setBackground(new java.awt.Color(212, 255, 242));
        btnMateriales.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMateriales.setText("Materiales");
        btnMateriales.setBorder(null);
        btnMateriales.setBorderPainted(false);
        btnMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMateriales.setMaximumSize(new java.awt.Dimension(58, 17));
        btnMateriales.setMinimumSize(new java.awt.Dimension(58, 17));
        btnMateriales.setPreferredSize(new java.awt.Dimension(58, 17));
        btnMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMaterialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMaterialesMouseExited(evt);
            }
        });
        btnMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesActionPerformed(evt);
            }
        });
        pnMenu.add(btnMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 44));

        btnInformes.setBackground(new java.awt.Color(212, 255, 242));
        btnInformes.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.setBorder(null);
        btnInformes.setBorderPainted(false);
        btnInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformes.setMaximumSize(new java.awt.Dimension(58, 17));
        btnInformes.setMinimumSize(new java.awt.Dimension(58, 17));
        btnInformes.setPreferredSize(new java.awt.Dimension(58, 17));
        btnInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformesMouseExited(evt);
            }
        });
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        pnMenu.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 300, 44));

        btnRegistroMateriales.setBackground(new java.awt.Color(212, 255, 242));
        btnRegistroMateriales.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistroMateriales.setText("Suministro de materiales");
        btnRegistroMateriales.setBorder(null);
        btnRegistroMateriales.setBorderPainted(false);
        btnRegistroMateriales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistroMateriales.setMaximumSize(new java.awt.Dimension(58, 17));
        btnRegistroMateriales.setMinimumSize(new java.awt.Dimension(58, 17));
        btnRegistroMateriales.setPreferredSize(new java.awt.Dimension(58, 17));
        btnRegistroMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroMaterialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroMaterialesMouseExited(evt);
            }
        });
        btnRegistroMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroMaterialesActionPerformed(evt);
            }
        });
        pnMenu.add(btnRegistroMateriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 300, 44));

        pnTitulo.setBackground(new java.awt.Color(201, 239, 228));

        lbTitulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("TITULO");

        lbBienvenida.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lbBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbBienvenida.setText("Bienvenido/a ----");

        javax.swing.GroupLayout pnTituloLayout = new javax.swing.GroupLayout(pnTitulo);
        pnTitulo.setLayout(pnTituloLayout);
        pnTituloLayout.setHorizontalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTituloLayout.createSequentialGroup()
                        .addComponent(lbBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnTituloLayout.setVerticalGroup(
            pnTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTituloLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lbBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnHeader.setBackground(new java.awt.Color(255, 255, 255));
        pnHeader.setPreferredSize(new java.awt.Dimension(100, 30));
        pnHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnHeaderMouseDragged(evt);
            }
        });
        pnHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnHeaderMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        lbExit.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        lbExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExit.setText("X");
        lbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnHeaderLayout = new javax.swing.GroupLayout(pnHeader);
        pnHeader.setLayout(pnHeaderLayout);
        pnHeaderLayout.setHorizontalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addGap(0, 1248, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnHeaderLayout.setVerticalGroup(
            pnHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHeaderLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnContenido.setPreferredSize(new java.awt.Dimension(968, 617));

        javax.swing.GroupLayout pnContenidoLayout = new javax.swing.GroupLayout(pnContenido);
        pnContenido.setLayout(pnContenidoLayout);
        pnContenidoLayout.setHorizontalGroup(
            pnContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnContenidoLayout.setVerticalGroup(
            pnContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnBgLayout = new javax.swing.GroupLayout(pnBg);
        pnBg.setLayout(pnBgLayout);
        pnBgLayout.setHorizontalGroup(
            pnBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(pnBgLayout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(pnBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnBgLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnBgLayout.setVerticalGroup(
            pnBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBgLayout.createSequentialGroup()
                .addComponent(pnHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnBgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBgLayout.createSequentialGroup()
                        .addComponent(pnTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseClicked
        System.exit(0);
        //this.setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lbExitMouseClicked

    private void lbExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseEntered
        btnExit.setBackground(Color.red);
        lbExit.setForeground(Color.white);
    }//GEN-LAST:event_lbExitMouseEntered

    private void lbExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbExitMouseExited
        btnExit.setBackground(Color.white);
        lbExit.setForeground(Color.black);
    }//GEN-LAST:event_lbExitMouseExited

    private void pnHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_pnHeaderMousePressed

    private void pnHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse,y- yMouse);
    }//GEN-LAST:event_pnHeaderMouseDragged

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        agregarJPanel(new VistaClientes(), "CLIENTES");
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEncargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncargosActionPerformed
        agregarJPanel(new VistaEncargos(), "ADMINISTRACIÓN DE ENCARGOS");
    }//GEN-LAST:event_btnEncargosActionPerformed

    private void btnRegistroEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroEntregasActionPerformed
        agregarJPanel(new VistaRegistroEncargos(), "REGISTRO ENCARGOS");
    }//GEN-LAST:event_btnRegistroEntregasActionPerformed

    private void btnRegistroEntregasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEntregasMouseEntered
        hoverButtonsEntered(btnRegistroEntregas);//9CDDF0
    }//GEN-LAST:event_btnRegistroEntregasMouseEntered

    private void btnRegistroEntregasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroEntregasMouseExited
        hoverButtonExited(btnRegistroEntregas); //9EFFFF
    }//GEN-LAST:event_btnRegistroEntregasMouseExited

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        agregarJPanel(new VistaProveedores(), "PROVEEDORES");
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnColegiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColegiosActionPerformed
        agregarJPanel(new VistaColegios(), "COLEGIOS");
    }//GEN-LAST:event_btnColegiosActionPerformed

    private void btnEncargosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncargosMouseEntered
        hoverButtonsEntered(btnEncargos);
    }//GEN-LAST:event_btnEncargosMouseEntered

    private void btnEncargosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEncargosMouseExited
        hoverButtonExited(btnEncargos);
    }//GEN-LAST:event_btnEncargosMouseExited

    private void btnClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseEntered
        hoverButtonsEntered(btnClientes);
    }//GEN-LAST:event_btnClientesMouseEntered

    private void btnClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientesMouseExited
        hoverButtonExited(btnClientes);
    }//GEN-LAST:event_btnClientesMouseExited

    private void btnPrendasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrendasMouseEntered
        hoverButtonsEntered(btnPrendas);
    }//GEN-LAST:event_btnPrendasMouseEntered

    private void btnPrendasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrendasMouseExited
        hoverButtonExited(btnPrendas);
    }//GEN-LAST:event_btnPrendasMouseExited

    private void btnUniformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUniformesMouseEntered
        hoverButtonsEntered(btnUniformes);
    }//GEN-LAST:event_btnUniformesMouseEntered

    private void btnUniformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUniformesMouseExited
        hoverButtonExited(btnUniformes);
    }//GEN-LAST:event_btnUniformesMouseExited

    private void btnColegiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColegiosMouseEntered
        hoverButtonsEntered(btnColegios);
    }//GEN-LAST:event_btnColegiosMouseEntered

    private void btnColegiosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColegiosMouseExited
        hoverButtonExited(btnColegios);
    }//GEN-LAST:event_btnColegiosMouseExited

    private void btnProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseEntered
        hoverButtonsEntered(btnProveedores);
    }//GEN-LAST:event_btnProveedoresMouseEntered

    private void btnProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseExited
        hoverButtonExited(btnProveedores);
    }//GEN-LAST:event_btnProveedoresMouseExited

    private void btnRegistroUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroUsersMouseEntered
        hoverButtonsEntered(btnRegistroUsers);
    }//GEN-LAST:event_btnRegistroUsersMouseEntered

    private void btnRegistroUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroUsersMouseExited
        hoverButtonExited(btnRegistroUsers);
    }//GEN-LAST:event_btnRegistroUsersMouseExited

    private void btnRegistroUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroUsersActionPerformed
        agregarJPanel(new VistaRegistroUsuarios(), "USUARIOS");
    }//GEN-LAST:event_btnRegistroUsersActionPerformed

    private void lbMenuTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuTitleMouseClicked
        agregarJPanel(new VistaInicioAdmin(), "INICIO");
    }//GEN-LAST:event_lbMenuTitleMouseClicked

    private void btnMaterialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaterialesMouseEntered

    private void btnMaterialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaterialesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaterialesMouseExited

    private void btnMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesActionPerformed
        agregarJPanel(new VistaMateriales(), "MATERIAS PRIMAS");
    }//GEN-LAST:event_btnMaterialesActionPerformed

    private void btnInformesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformesMouseEntered

    private void btnInformesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformesMouseExited

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        agregarJPanel(new VistaInformes(), "INFORMES");
    }//GEN-LAST:event_btnInformesActionPerformed

    private void btnPrendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrendasActionPerformed
        agregarJPanel(new VistaPrendas(), "PRENDAS");
    }//GEN-LAST:event_btnPrendasActionPerformed

    private void btnUniformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniformesActionPerformed
        agregarJPanel(new VistaUniformes(), "UNIFORMES");
    }//GEN-LAST:event_btnUniformesActionPerformed

    private void btnRegistroMaterialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMaterialesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroMaterialesMouseEntered

    private void btnRegistroMaterialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroMaterialesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistroMaterialesMouseExited

    private void btnRegistroMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMaterialesActionPerformed
        agregarJPanel(new VistaSuministro(), "SUMINISTROS");
    }//GEN-LAST:event_btnRegistroMaterialesActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipalAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipalAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnColegios;
    private javax.swing.JButton btnEncargos;
    private javax.swing.JPanel btnExit;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnMateriales;
    private javax.swing.JButton btnPrendas;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnRegistroEntregas;
    private javax.swing.JButton btnRegistroMateriales;
    private javax.swing.JButton btnRegistroUsers;
    private javax.swing.JButton btnUniformes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbBienvenida;
    public javax.swing.JLabel lbExit;
    private javax.swing.JLabel lbMenuTitle;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnBg;
    private javax.swing.JPanel pnContenido;
    private javax.swing.JPanel pnHeader;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnTitulo;
    // End of variables declaration//GEN-END:variables
}
